/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lpan_mine_jnitest_HelloJni */

#ifndef _Included_com_lpan_mine_jnitest_HelloJni
#define _Included_com_lpan_mine_jnitest_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lpan_mine_jnitest_HelloJni
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lpan_mine_jnitest_HelloJni_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
