/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lpan_mine_jnitest_HelloJni */

#ifndef _Included_com_lpan_mine_jnitest_HelloJni
#define _Included_com_lpan_mine_jnitest_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lpan_mine_jnitest_HelloJni
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lpan_mine_jnitest_HelloJni_test
  (JNIEnv *, jclass);

/*
 * Class:     com_lpan_mine_jnitest_HelloJni
 * Method:    testObjMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lpan_mine_jnitest_HelloJni_testObjMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_lpan_mine_jnitest_HelloJni
 * Method:    testIntParams
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lpan_mine_jnitest_HelloJni_testIntParams
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_lpan_mine_jnitest_HelloJni
 * Method:    testIntArrParams
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_lpan_mine_jnitest_HelloJni_testIntArrParams
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_lpan_mine_jnitest_HelloJni
 * Method:    testStringParams
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lpan_mine_jnitest_HelloJni_testStringParams
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_lpan_mine_jnitest_HelloJni
 * Method:    testCInvokeJava
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lpan_mine_jnitest_HelloJni_testCInvokeJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
